import httpx
from typing import Dict, Any
from app.config import settings

class SarvamClient:
    def __init__(self):
        self.api_key = settings.SARVAM_API_KEY
        self.base_url = settings.SARVAM_BASE_URL
        self.headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
    async def translate_intent(self, user_transcript: str) -> str:
        '''
        Mocks a call to the Sarvam LLM for intent recognition.
        '''
        if not self.api_key:
            return "NO_API_KEY_CONFIGURED"
            
        async with httpx.AsyncClient() as client:
            try:
                # Example Sarvam Chat Completion payload
                payload = {
                    "model": "sarvam-chat",
                    "messages": [{"role": "user", "content": user_transcript}],
                    "temperature": 0.3
                }
                
                # We would call the actual Sarvam endpoint here
                # response = await client.post(f"{self.base_url}/v1/chat/completions", json=payload, headers=self.headers)
                # response.raise_for_status()
                # return response.json()['choices'][0]['message']['content']
                
                return "Mock intent generated by Sarvam AI!"
            
            except Exception as e:
                print(f"Error calling Sarvam: {e}")
                return "ERROR_FETCHING_INTENT"
